//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmenBackEnd.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmenEntities : DbContext
    {
        public FilmenEntities()
            : base("name=FilmenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<cinema> cinemas { get; set; }
        public virtual DbSet<lounge> lounges { get; set; }
        public virtual DbSet<seat> seats { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<viewing> viewings { get; set; }
    }
}
