//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmenBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public viewing()
        {
            this.bookings = new HashSet<booking>();
        }
    
        public int id { get; set; }
        public int loungeid { get; set; }
        public System.DateTime date { get; set; }
        public string moviedbid { get; set; }
        public bool bookable { get; set; }
        public System.DateTime created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { internal get; set; }
        public virtual lounge lounge { internal get; set; }
    }
}
